---
- name: synchronize journalbeat repo
  git:
    repo: "https://github.com/mheese/journalbeat.git"
    dest: "/usr/local/go/src/github.com/mheese/journalbeat.git"
    version: "{{ journalbeat_version }}"
    update: true
  register: newRelease

- name: build and install journalbeat
  shell: "export GOPATH=/usr/local/go && export GOBIN=${GOPATH}/bin && cd /usr/local/go/src/github.com/mheese/journalbeat && go get && go install"
  when: newRelease.changed or journalbeat_reinstall is defined

- name: ensure executable files
  file:
    path: "/usr/local/go/bin/journalbeat"
    owner: root
    mode: "0755"

- name: copy service file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "journalbeat.service.j2"
      dest: "/etc/systemd/system/journalbeat.service"
    - src: "journalbeat.yml.j2"
      dest: "/etc/journalbeat.yml"
  notify:
    - reload systemd
    - restart journalbeat

- meta: flush_handlers

- name: ensure service started
  service:
    name: journalbeat
    state: started
    enabled: true
